apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-webhook-proxy
  namespace: monitoring
  labels:
    app: discord-webhook-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discord-webhook-proxy
  template:
    metadata:
      labels:
        app: discord-webhook-proxy
    spec:
      containers:
      - name: discord-webhook-proxy
        image: discord-webhook-proxy:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: FLASK_ENV
          value: "production"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: discord-webhook-proxy
  namespace: monitoring
  labels:
    app: discord-webhook-proxy
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: discord-webhook-proxy
