apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-server-config
  namespace: argocd
data:
  server.insecure: "true"
  admin.enabled: "false"
  users.anonymous.enabled: "true"
  server.disable.auth: "true"
  url: "http://localhost:8080"
