apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  - argocd-server-config.yaml

patches:
  - target:
      version: v1
      kind: ConfigMap
      name: argocd-cm
      namespace: argocd
    patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: argocd-cm
        namespace: argocd
      data:
        users.anonymous.enabled: "true"
        admin.enabled: "false"
  - target:
      version: v1
      kind: ConfigMap
      name: argocd-rbac-cm
      namespace: argocd
    patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: argocd-rbac-cm
        namespace: argocd
      data:
        policy.default: role:admin
  - target:
      version: v1
      kind: ConfigMap
      name: argocd-cmd-params-cm
      namespace: argocd
    patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: argocd-cmd-params-cm
        namespace: argocd
      data:
        server.insecure: "true"
        server.disable.auth: "true"
